"""translation are added

Revision ID: 498af5b4001b
Revises: 61c26fc15f93
Create Date: 2025-03-18 15:32:07.729049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498af5b4001b'
down_revision: Union[str, None] = '61c26fc15f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('name_uz', sa.String(), nullable=True))
    op.add_column('service', sa.Column('name_ru', sa.String(), nullable=True))
    op.add_column('service', sa.Column('name_en', sa.String(), nullable=True))
    op.add_column('service', sa.Column('description_uz', sa.String(), nullable=True))
    op.add_column('service', sa.Column('description_ru', sa.String(), nullable=True))
    op.add_column('service', sa.Column('description_en', sa.String(), nullable=True))
    op.drop_constraint('service_name_key', 'service', type_='unique')
    op.create_unique_constraint(None, 'service', ['name_uz'])
    op.drop_column('service', 'name')
    op.drop_column('service', 'description')
    op.add_column('service_category', sa.Column('name_uz', sa.String(), nullable=True))
    op.add_column('service_category', sa.Column('name_ru', sa.String(), nullable=True))
    op.add_column('service_category', sa.Column('name_en', sa.String(), nullable=True))
    op.drop_constraint('service_category_name_key', 'service_category', type_='unique')
    op.create_unique_constraint(None, 'service_category', ['name_uz'])
    op.drop_column('service_category', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_category', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service_category', type_='unique')
    op.create_unique_constraint('service_category_name_key', 'service_category', ['name'])
    op.drop_column('service_category', 'name_en')
    op.drop_column('service_category', 'name_ru')
    op.drop_column('service_category', 'name_uz')
    op.add_column('service', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('service', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service', type_='unique')
    op.create_unique_constraint('service_name_key', 'service', ['name'])
    op.drop_column('service', 'description_en')
    op.drop_column('service', 'description_ru')
    op.drop_column('service', 'description_uz')
    op.drop_column('service', 'name_en')
    op.drop_column('service', 'name_ru')
    op.drop_column('service', 'name_uz')
    # ### end Alembic commands ###
