"""new filed is price

Revision ID: 75311d4b1907
Revises: 539513be4fc9
Create Date: 2025-04-05 17:17:40.794602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75311d4b1907'
down_revision: Union[str, None] = '539513be4fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('price', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'price')
    # ### end Alembic commands ###
